const cuisines = [
  "American",
  "Asian",
  "Bakery",
  "Bar food",
  "Beverage-oriented",
  "Burgers",
  "Cafe",
  "Canadian",
  "Chinese",
  "Desserts",
  "Donuts",
  "Grill",
  "Indian",
  "Italian",
  "Peruvian",
  "Japanese",
  "Middle Eastern",
  "Pizza",
  "Sandwhiches",
  "Sushi",
  "Thai",
];

const restaurantType = [
  "Bakeries",
  "Bars",
  "Beer Gardens",
  "Beverage Shops",
  "Bistros",
  "Cafés",
  "Casual Dining",
  "Clubs",
  "Cocktail Bars",
  "Coffee Shops",
  "Dessert Parlors",
  "Fast Food",
  "Fine Dining",
  "Food Courts",
  "Food Trucks",
  "Ice Cream",
  "Izakaya",
  "Juice Bar",
  "Lounges",
  "Noodle Shops",
  "Pizzerias",
  "Pubs",
  "Quick Bites",
  "Sandwich Shops",
  "Steakhouse",
  "Sweet Shops",
  "Wine Bars",
];
