export const yelpStates = [
  "Arizona",
  "California",
  "Colorado",
  "Connecticut",
  "Florida",
  "Georgia",
  "Hawaii",
  "Iowa",
  "Idaho",
  "Illinois",
  "Indiana",
  "Kentucky",
  "Louisiana",
  "Massachusetts",
  "Maryland",
  "Michigan",
  "Minnesota",
  "Missouri",
  "North Carolina",
  "New Jersey",
  "New Mexico",
  "Nevada",
  "New York",
  "Ohio",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "Tennessee",
  "Texas",
  "Utah",
  "Virginia",
  "Vermont",
  "Washington",
  "Wisconsin",
];
export const yelpCitiesUS = {
  // prettier-ignore
  Arizona: ["Phoenix", "Scottsdale", "Tempe", "Tucson"],
  California: [
    "Alameda",
    "Albany",
    "Alhambra",
    "Anaheim",
    "Belmont",
    "Berkeley",
    "Beverly Hills",
    "Big Sur",
    "Burbank",
    "Concord",
    "Costa Mesa",
    "Culver City",
    "Cupertino",
    "Daly City",
    "Davis",
    "Dublin",
    "Emeryville",
    "Foster City",
    "Fremont",
    "Glendale",
    "Hayward",
    "Healdsburg",
    "Huntington Beach",
    "Irvine",
    "La Jolla",
    "Livermore",
    "Long Beach",
    "Los Altos",
    "Los Angeles",
    "Los Gatos",
    "Marina del Rey",
    "Menlo Park",
    "Mill Valley",
    "Millbrae",
    "Milpitas",
    "Monterey",
    "Mountain View",
    "Napa",
    "Newark",
    "Newport Beach",
    "Oakland",
    "Orange County",
    "Palo Alto",
    "Park La Brea",
    "Pasadena",
    "Pleasanton",
    "Redondo Beach",
    "Redwood City",
    "Sacramento",
    "San Bruno",
    "San Carlos",
    "San Diego",
    "San Francisco",
    "San Jose",
    "San Leandro",
    "San Mateo",
    "San Rafael",
    "Santa Barbara",
    "Santa Clara",
    "Santa Cruz",
    "Santa Monica",
    "Santa Rosa",
    "Sausalito",
    "Sonoma",
    "South Lake Tahoe",
    "Stockton",
    "Studio City",
    "Sunnyvale",
    "Torrance",
    "Union City",
    "Venice",
    "Walnut Creek",
    "West Hollywood",
    "West Los Angeles",
    "Westwood",
    "Yountville",
  ],
  Colorado: ["Boulder", "Denver"],
  Connecticut: ["Hartford", "New Haven"],
  Florida: [
    "Fort Lauderdale",
    "Gainesville",
    "Miami",
    "Miami Beach",
    "Orlando",
    "Tampa",
  ],
  Georgia: ["Atlanta", "Savannah"],
  Hawaii: ["Honolulu", "Lahaina"],
  Iowa: ["Iowa City"],
  Idaho: ["Boise"],
  Illinois: ["Chicago", "Evanston", "Naperville", "Schaumburg", "Skokie"],
  Indiana: ["Bloomington", "Indianapolis"],
  Kentucky: ["Louisville"],
  Louisiana: ["New Orleans"],
  //  prettier-ignore
  Massachusetts: [ 'Allston', 'Boston', 'Brighton', 'Brookline', 'Cambridge', 'Somerville',],
  Maryland: ["Baltimore"],
  Michigan: ["Ann Arbor", "Detroit"],
  Minnesota: ["Minneapolis", "Saint Paul"],
  Missouri: ["Kansas City", "Saint Louis"],
  "North Carolina": ["Charlotte", "Durham", "Raleigh"],
  "New Jersey": ["Newark", "Princeton"],
  "New Mexico": ["Albuquerque", "Santa Fe"],
  Nevada: ["Las Vegas", "Reno"],
  "New York": ["Brooklyn", "Long Island City", "New York", "Flushing"],
  Ohio: ["Cincinnati", "Cleveland", "Columbus"],
  Oregon: ["Portland", "Salem"],
  Pennsylvania: ["Philadelphia", "Pittsburgh"],
  "Rhode Island": ["Providence"],
  "South Carolina": ["Charleston"],
  Tennessee: ["Memphis", "Nashville"],
  Texas: ["Austin", "Dallas", "Houston", "San Antonio"],
  Utah: ["Salt Lake City"],
  Virginia: ["Alexandria", "Arlington", "Richmond"],
  Vermont: ["Burlington"],
  Washington: ["Bellevue", "Redmond", "Seattle"],
  Wisconsin: ["Madison", "Milwaukee"],
};

export const yelpCitiesCA = [
  "Calgary",
  "Edmonton",
  "Halifax",
  "Montréal",
  "Ottawa",
  "Toronto",
  "Vancouver",
];
