export const countries = [

  { code: "AR", label: "Argentina", phone: "54" },
  {
    code: "AU",
    label: "Australia",
    phone: "61",
    suggested: true,
  },
  { code: "AT", label: "Austria", phone: "43" },
  { code: "BE", label: "Belgium", phone: "32" },
  { code: "BR", label: "Brazil", phone: "55" },
  {
    code: "CA",
    label: "Canada",
    phone: "1",
    suggested: true,
  },
  { code: "CL", label: "Chile", phone: "56" },
  { code: "CZ", label: "Czech Republic", phone: "420" },
  { code: "DK", label: "Denmark", phone: "45" },
  { code: "FI", label: "Finland", phone: "358" },
  {
    code: "FR",
    label: "France",
    phone: "33",
    suggested: true,
  },
  {
    code: "DE",
    label: "Germany",
    phone: "49",
    suggested: true,
  },
  { code: "HK", label: "Hong Kong", phone: "852" },
  { code: "IT", label: "Italy", phone: "39" },
  {
    code: "JP",
    label: "Japan",
    phone: "81",
    suggested: true,
  },
  { code: "MY", label: "Malaysia", phone: "60" },
  { code: "MX", label: "Mexico", phone: "52" },
  { code: "NZ", label: "New Zealand", phone: "64" },
  { code: "NO", label: "Norway", phone: "47" },
  { code: "PH", label: "Philippines", phone: "63" },
  { code: "PL", label: "Poland", phone: "48" },
  { code: "PT", label: "Portugal", phone: "351" },
  { code: "IE", label: "Ireland", phone: "353" },
  { code: "SG", label: "Singapore", phone: "65" },
  { code: "ES", label: "Spain", phone: "34" },
  { code: "SE", label: "Sweden", phone: "46" },
  { code: "CH", label: "Switzerland", phone: "41" },
  {
    code: "TW",
    label: "Taiwan, Province of China",
    phone: "886",
  },
  { code: "NL", label: "Netherlands", phone: "31" },
  { code: "TR", label: "Turkey", phone: "90" },
  { code: "GB", label: "United Kingdom", phone: "44" },
  {
    code: "US",
    label: "United States",
    phone: "1",
    suggested: true,
  },
];
